simple_todo_list/urls.py
from django.contrib import admin
from django.urls import include, path
from .settings import DEBUG

urlpatterns = [
    path('', include('tasks.urls')),
    path("admin/", admin.site.urls),
]

if DEBUG:
    urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))

tasks/urls.py
from django.conf.urls import include
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('htmx/create-task-form/', views.create_task_form, name='create-task-form'),
    path('htmx/task-item/<id>/', views.task_item, name='task-item'),
    path('htmx/task-item/<id>/detailed/', views.task_detailed, name='task-detailed'),
    path('htmx/task-item/<id>/update/', views.task_update, name='task-update'),
    path('htmx/task-item/<id>/set-circular-next-status/',
         views.task_set_circular_next_status,
         name='task-set-circular-next-status'),
    path('htmx/task-item/<id>/delete/', views.task_delete, name='task-delete'),
]

tasks/models.py
from django.db import models

class Task(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(max_length=5000)

    # Constants for status
    TODO = "TODO"
    DOING = "DOING"
    DONE = "DONE"
    CANCELED = "CANCELED"
    STATUSES = [
        (TODO, "TODO"),
        (DOING, "DOING"),
        (DONE, "DONE"),
        (CANCELED, "CANCELED"),
    ]

    status = models.CharField(
        max_length=8,
        choices=STATUSES,
        default=TODO,
    )

    def __str__(self):
        return self.name

    @staticmethod
    def get_statuses():
        return list(map(lambda _: _[1], Task.STATUSES))

    def _get_status_index(self):
        return Task.get_statuses().index(self.status)

    def circular_next_status_index(self):
        current_index = self._get_status_index()
        next_index = (current_index + 1) % len(Task.STATUSES)
        return next_index

    def circular_next_status(self):
        next_index = self.circular_next_status_index()
        return Task.get_statuses()[next_index]

    def set_circular_next_status(self):
        self.status = self.circular_next_status()
        self.save()

class Tasks:
    @staticmethod
    def get_count_by_status(status: str):
        return Task.objects.filter(status=status).count()

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'name',
            'description',
            'status'
        ]

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponse, HttpResponseNotAllowed
from .models import Task
from .forms import TaskForm

def index(request):
    tasks = Task.objects.all()
    task_form = TaskForm(request.POST or None)

    if request.method == "POST":
        if task_form.is_valid():
            new_task = task_form.save(commit=False)
            new_task.save()
            print(f"{new_task.id=}")
            return redirect("tasks:task-item", id=new_task.id)

        return render(request, "partials/task_form.html", context={
            "task_form": task_form
        })

    context = {
        'tasks': tasks,
        'task_form': task_form,
    }

    return render(request, 'tasks/index.html', context)

def create_task_form(request):
    task_form = TaskForm()

    context = {
        'task_form': task_form,
    }

    return render(request, "partials/task_form.html", context)

def task_item(request, id):
    task = get_object_or_404(Task, id=id)

    context = {
        "task": task
    }

    return render(request, "partials/task_item.html", context)

def task_detailed(request, id):
    task = get_object_or_404(Task, id=id)

    context = {
        "task": task
    }

    return render(request, "partials/task_detailed.html", context)

def task_update(request, id):
    task = get_object_or_404(Task, id=id)
    task_form = TaskForm(request.POST or None, instance=task)

    if request.method == "POST":
        if task_form.is_valid():
            task_form.save()
            return redirect("tasks:task-item", id=task.id)

    context = {
        'task': task,
        'task_form': task_form,
    }

    return render(request, "partials/task_form.html", context)

def task_set_circular_next_status(request, id):
    task = get_object_or_404(Task, id=id)

    if request.method == "POST":
        task.set_circular_next_status()

    context = {
        'task': task,
    }

    return render(request, "partials/task_item.html", context)

def task_delete(request, id):
    task = get_object_or_404(Task, id=id)

    if request.method == "POST":
        task.delete()
        return HttpResponse("")
    return HttpResponseNotAllowed([ "POST" ])

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% tailwind_css %}
    <script src="https://unpkg.com/htmx.org@1.9.3" integrity="sha384-lVb3Rd/Ca0AxaoZg5sACe8FJKF0tnUgR2Kd7ehUOG5GCcROv5uBIZsOqovBAcWua" crossorigin="anonymous"></script>
    <title>{% block title %}Simple TODO List{% endblock %}</title>
  </head>
  <body>
    <div class="flex flex-col justify-center w-full max-w-2xl mx-auto">
      {% block content %}
      {% endblock %}
    </div>

    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
  </body>
</html>

templates/partials/task_detailed.html
<div hx-target="this" class="p-2 border rounded-lg inline-flex gap-2 my-2 bg-gray-200">
  <div class="grid grid-cols-3 gap-2 justify-center w-full max-w-2xl mx-auto">
    <div class="col-span-3">
      <dl class="row flex flex-inline">
        <dt class="col-sm-3 font-bold mr-2">Status:</dt>
        {% if task.status == "TODO" %}
        <dd class="font-semibold text-green-500"
        {% elif task.status == "DOING" %}
        <dd class="font-semibold text-yellow-500"
        {% elif task.status == "DONE" or task.status == "CANCELED" %}
        <dd class="font-semibold text-gray-500"
        {% endif %}
        >
          {{ task.status }}
        </dd>
      </dl>
      <dl class="row flex flex-inline flex-wrap">
        <dt class="col-sm-3 font-bold mr-2">Name:</dt>
        <dd class="col-sm-9 whitespace-pre-line">{{ task.name }}</dd>
      </dl>
      <dl class="flex flex-col flex-inline">
        <dt class="col-sm-3 font-bold mr-2">Description:</dt>
        <dd class="col-sm-9 whitespace-pre-line">{{ task.description }}</dd>
      </dl>
    </div>

    <button type="button"
     hx-post="{% url 'tasks:task-item' task.id %}"
     hx-swap="outerHTML"
     class="inline-block px-5 py-1.5 bg-green-600 text-white font-medium text-xs leading-tight
            uppercase rounded shadow-md hover:bg-green-700 hover:shadow-lg focus:bg-green-700
            focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-800 active:shadow-lg
            transition duration-150 ease-in-out">
      Back
    </button>

    <button type="button"
     hx-post="{% url 'tasks:task-update' task.id %}"
     hx-swap="outerHTML"
     class="inline-block px-5 py-1.5 bg-blue-600 text-white font-medium text-xs leading-tight
            uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700
            focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg
            transition duration-150 ease-in-out">
      Update
    </button>

    <button type="button"
     hx-post="{% url 'tasks:task-delete' task.id %}"
     hx-swap="outerHTML"
     class="inline-block px-5 py-1.5 bg-red-600 text-white font-medium text-xs leading-tight
            uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700
            focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg
            transition duration-150 ease-in-out">
      Delete
    </button>
  </div>
</div>

templates/partials/task_form.html
{% load tailwind_filters %}

<div hx-target="this" hx-swap="outerHTML">
  <form method="POST">
    {% csrf_token %}
    {{ task_form|crispy }}
    {% if task %}
      <button type="submit" hx-post="{% url 'tasks:task-update' task.id %}">Submit</button>
      <button hx-post="{% url 'tasks:task-item' task.id %}">Cancel</button>
    {% else %}
      <button type="submit" hx-post=".">Submit</button>
    {% endif %}
  </form>
</div>

templates/partials/task_item.html
<div hx-target="this" class="p-2 border rounded-lg inline-flex gap-2 my-2 bg-gray-200">
  {% if task.status == "TODO" %}
  <p class="font-semibold text-green-500"
  {% elif task.status == "DOING" %}
  <p class="font-semibold text-yellow-500"
  {% elif task.status == "DONE" or task.status == "CANCELED" %}
  <p class="font-semibold text-gray-500"
  {% endif %}
     hx-post="{% url 'tasks:task-set-circular-next-status' task.id %}"
     hx-swap="outerHTML">
    {{ task.status }}
  </p>

  <p class="font-semibold"
     hx-post="{% url 'tasks:task-detailed' task.id %}"
     hx-swap="outerHTML">
     {{ task.name }}
  </p>

  <p>{{ task.description | truncatechars:40 }}</p>

  <button type="button"
	  hx-post="{% url 'tasks:task-update' task.id %}"
	  hx-swap="outerHTML"
	  class="inline-block px-5 py-1.5 bg-blue-600 text-white font-medium text-xs leading-tight
          uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700
          focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg
          transition duration-150 ease-in-out ml-auto">
    Update
  </button>
  <button type="button"
	  hx-post="{% url 'tasks:task-delete' task.id %}"
	  hx-swap="outerHTML"
	  class="inline-block px-5 py-1.5 bg-red-600 text-white font-medium text-xs leading-tight
          uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700
          focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg
          transition duration-150 ease-in-out">
    Delete
  </button>
</div>

templates/tasks/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1 class="text-3xl font-bold text-center my-2">Tasks</h1>

  <button type="button"
	  hx-get="{% url 'tasks:create-task-form' %}"
	  hx-target="#task-items"
	  hx-swap="beforeend"
	  class="inline-block px-14 py-2.5 bg-green-600 text-white font-medium text-xs leading-tight
          uppercase rounded shadow-md hover:bg-green-700 hover:shadow-lg focus:bg-green-700
          focus:shadow-lg focus:outline-none focus:ring-0 active:bg-green-800 active:shadow-lg
          transition duration-150 ease-in-out mx-auto">
    Add a new task
  </button>

  <div id="task-items" class="flex flex-col">
    {% for task in tasks %}
      {% include "partials/task_item.html" %}
    {% endfor %}
  </div>
{% endblock %}